tomcat:
    image: tomcat:7
    restart: always
    ports:
      - 7080:8080
    links:
      - db
      - python
    
db:
    image: mongo
    restart: always
    ports: 
      - 27017:27017
  
python:
    image: python:2.7
    restart: always
    links: 
      - db
   